const styles = {
  container: {
    width: "700px",
    margin: "30px auto",
    padding: "20px",
    border: "1px solid #ccc",
    borderRadius: "10px",
    backgroundColor: "white",
  },
  chatBox: {
    height: "300px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    border: "1px solid #ddd",
    borderRadius: "10px",
    padding: "10px",
    marginBottom: "10px",
    background: "#fafafa",
  },
  message: {
    maxWidth: "80%",
    padding: "10px",
    borderRadius: "10px",
    wordWrap: "break-word",
  },
  inputContainer: {
    display: "flex",
    gap: "10px",
  },
  input: {
    flex: 1,
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #da9a9aff",
    marginBottom: "6px",
    height: "50px",
  },
  textarea: {
    width: "100%",
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    marginTop: "10px",
  },
  button: {
    padding: "10px 15px",
    border: "none",
    borderRadius: "5px",
    backgroundColor: "#007BFF",
    color: "white",
    cursor: "pointer",
  },
  tabBar: {
    display: "flex",
    marginBottom: "15px",
    gap: "10px",
  },
  tab: {
    flex: 1,
    padding: "10px",
    border: "1px solid #ccc",
    borderRadius: "5px",
    background: "#f5f5f5",
    cursor: "pointer",
  },
  activeTab: {
    flex: 1,
    padding: "10px",
    border: "1px solid #b32d2d",
    borderRadius: "5px",
    background: "#b32d2d",
    color: "white",
    cursor: "pointer",
  },
  summaryCard: {
    backgroundColor: "#fff8e1",
    border: "1px solid #fbc02d",
    borderRadius: "12px",
    padding: "15px",
    margin: "10px 0",
    whiteSpace: "pre-wrap",
  },
  symptomHeader: {
    fontWeight: "bold",
    marginTop: "8px",
  },
  doctorNote: {
    fontStyle: "italic",
    color: "#555",
    marginLeft: "20px",
    paddingLeft: "10px",
    borderLeft: "3px solid #ccc",
  },
  adminPanel: {
    marginTop: "10px",
  },
  ruleCard: {
    border: "1px solid #ccc",
    borderRadius: "8px",
    marginBottom: "10px",
  },
  ruleHeader: {
    padding: "8px 12px",
    background: "#f5f5f5",
    display: "flex",
    justifyContent: "space-between",
    cursor: "pointer",
  },
  ruleList: {
    padding: "8px 20px",
    background: "#fafafa",
  },
  chatButton: {
    border: "none",
    borderRadius: "5px",
    color: "white",
    cursor: "pointer",
    width: "50px",
    height: "50px",
  },
};

export default styles;
